### ISSUE TITLE
Question, why is this an IOC Container

### ISSUE THREAD

**Issue by linonetwo** [vilic/entrance-decorator#1]
To be a dependency injection framework, it usually means inject an instance of class into another, but from readme, there seems to be no such action?

**Comment by vilicvane** [comment]
This is just a simple method to manage dependent providers, it is up to the developer to find a proper way handling how to inject those providers into something like React components.

For example, we use React `Context` API for this purpose:

```tsx
ReactDOM.render(
  <EntrancesContext.Provider value={entrances}>
    <App />
  </EntrancesContext.Provider>,
  document.getElementById('app'),
);
```

```tsx
const App = () => {
  const {messageService} = useContext(EntrancesContext);

  // ...
};
```

**Comment by linonetwo** [comment]
I'm too young too simple to understand these...My university didn't teach me this.
